# Changes:
# - Added new schema name Caretaker

openapi: "3.0.0"
info:
  version: 1.0.1
paths:
components:
  schemas:
    Caretaker:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string